"""empty message

Revision ID: 025418356636
Revises: 3c0521294935
Create Date: 2023-09-29 03:40:04.287333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025418356636'
down_revision = '3c0521294935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=24), autoincrement=False, nullable=True))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
