"""empty message

Revision ID: 9917f7d7ca4d
Revises: 53c2b1ef199d
Create Date: 2023-10-02 05:32:10.788364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9917f7d7ca4d'
down_revision = '53c2b1ef199d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=24), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
